### ISSUE TITLE
send_money() using a funding source ID that is not default results in 500 Internal Server Error

### ISSUE THREAD

**Issue by mwdoran8** [mmohades/Venmo#30]
When I try to send money using an alternative payment method (not my default) I get the following error.

Traceback (most recent call last):
  File "C:\Users\mwdor\Documents\GitHub\phone-bill\pay_dad.py", line 26, in <module>
    venmo.payment.send_money(payment, message, recipient.id, funding_source_id=payment_method)
  File "C:\Users\mwdor\AppData\Local\Programs\Python\Python39\lib\site-packages\venmo_api\apis\payment_api.py", line 124, in send_money
    return self.__send_or_request_money(amount=amount,
  File "C:\Users\mwdor\AppData\Local\Programs\Python\Python39\lib\site-packages\venmo_api\apis\payment_api.py", line 237, in __send_or_request_money
    result = self.__api_client.call_api(resource_path=resource_path,
  File "C:\Users\mwdor\AppData\Local\Programs\Python\Python39\lib\site-packages\venmo_api\utils\api_client.py", line 58, in call_api
    return self.__call_api(resource_path=resource_path, method=method,
  File "C:\Users\mwdor\AppData\Local\Programs\Python\Python39\lib\site-packages\venmo_api\utils\api_client.py", line 103, in __call_api
    processed_response = self.request(method, url, session,
  File "C:\Users\mwdor\AppData\Local\Programs\Python\Python39\lib\site-packages\venmo_api\utils\api_client.py", line 139, in request
    validated_response = self.__validate_response(response, ok_error_codes=ok_error_codes)
  File "C:\Users\mwdor\AppData\Local\Programs\Python\Python39\lib\site-packages\venmo_api\utils\api_client.py", line 170, in __validate_response
    raise HttpCodeError(response=response)
venmo_api.models.exception.HttpCodeError: HTTP Status code is invalid. Could not make the request because -> 500 Internal Server Error.
Error: Invalid Json

**Comment by mwdoran8** [comment]
I'm sorry, this was due to a mistake of mine. I was using the wrong funding_source_id.
