### ISSUE TITLE
Bug With user.get_user_transactions()

### ISSUE THREAD

**Issue by zachgoldy** [mmohades/Venmo#49]
looks like get_user_transactions() is returning a 404 error. I've been working with get_user(), and get_user_friends_list(), which both work perfectly fine, but for some reason when I try get_user_transactions() with the same parameters I get the following error. 

Exception in thread Thread-14:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\venmo_api\utils\api_client.py", line 103, in __call_api
    processed_response = self.request(method, url, session,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\venmo_api\utils\api_client.py", line 139, in request
    validated_response = self.__validate_response(response, ok_error_codes=ok_error_codes)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\venmo_api\utils\api_client.py", line 170, in __validate_response
    raise HttpCodeError(response=response)
venmo_api.models.exception.HttpCodeError: HTTP Status code is invalid. Could not make the request because -> 404 Not Found.
Error: Invalid Json

**Comment by mmohades** [comment]
This looks like to be caused by passing an invalid user id. Are you still getting this error?

**Comment by mmohades** [comment]
Closing the issue due to inactivity. Please feel free to reopen it.
